services:
  centos7:
    image: rpmbuild/centos7
    environment:
    - VERSION
    - PKG
    volumes:
    - .:/workspace
    command: /workspace/build.sh ${PKG}

  rockylinux8:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.builder8
      args:
        UID: ${UID:-1000}
    image: rpmbuild/rpm-builder:rockylinux8
    environment:
    - VERSION
    - PKG
    volumes:
    - .:/workspace
    command: /workspace/build.sh ${PKG}

  rockylinux9:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.builder9
      args:
        UID: ${UID:-1000}
    image: rpmbuild/rpm-builder:rockylinux9
    environment:
    - VERSION
    - PKG
    volumes:
    - .:/workspace
    command: /workspace/build.sh ${PKG}
