name: Build CI

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Create RPM
      run: make prometheus
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: build/**/*.rpm
